#!/usr/bin/env python

import bson
import sys
import os

def convert_file_to_bson(file_path, bson_file_path):
    # Read the file data in binary mode
    with open(file_path, 'rb') as file:
        binary_data = file.read()

    # Convert binary data to BSON format
    bson_data = bson.dumps(binary_data)

    # Write BSON data to the BSON file
    with open(bson_file_path, 'wb') as bson_file:
        bson_file.write(bson_data)


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'convert':
        if len(sys.argv) > 2:
            input_file = sys.argv[2]
        else:
            input_file = input("Enter the file path: ")

        target_directory = input("Enter the target directory (leave empty for current directory): ")
        if target_directory:
            bson_file = os.path.join(target_directory, os.path.basename(input_file) + '.bson')
        else:
            bson_file = os.path.join(os.getcwd(), os.path.basename(input_file) + '.bson')

        # Convert the file to BSON
        convert_file_to_bson(input_file, bson_file)
    else:
        print("Usage: ./script.py convert <input_file>")

# To Run: convert_to_bson.py convert <input_file>

